# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnitedSE', '0003_filmstar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
